application:
version: 1
api_version: 1
runtime: python27
threadsafe: 1
handlers:
 - url: .*
   script: bot.app
 - url: /_ah/queue/deferred
   script: google.appengine.ext.deferred.deferred.application
   login: admin
builtins:
 - deferred: on
